# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
name: compiler
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  unittest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.11"
      - name: Decision Cell Compiler
        run: python3 -m a11oy_factory compile --cell lyte && python3 -m a11oy_factory compile --cell N1; test $? -eq 2
